name: Renew SSL Certificate
run-name: Renew SSL Certificate #${{ github.run_number }}

on:
  schedule:
    - cron: '0 0 1 */3 *'  # Run every 3 months on the 1st day
  workflow_dispatch:  # Allow manual triggering

env:
  DOMAIN: jotpac.com

jobs:
  display-date:
    runs-on: ubuntu-latest
    steps:
      - name: Display Current Date
        run: echo "Renewing SSL Certificate on $(date '+%Y-%m-%d')"
        
  renew-ssl:
    runs-on: self-hosted
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GoDaddy API credentials
      env:
        GODADDY_API_KEY: ${{ secrets.GODADDY_API_KEY }}
        GODADDY_API_SECRET: ${{ secrets.GODADDY_API_SECRET }}
      run: |
        echo "GODADDY_API_KEY=$GODADDY_API_KEY" >> $GITHUB_ENV
        echo "GODADDY_API_SECRET=$GODADDY_API_SECRET" >> $GITHUB_ENV

    - name: Run Certbot
      run: |
        chmod +x ./godaddy-dns-challenge.sh
        docker run --rm \
          -v /etc/letsencrypt:/etc/letsencrypt \
          -v $PWD:/scripts \
          -e GODADDY_API_KEY \
          -e GODADDY_API_SECRET \
          certbot/certbot:v2.10.0 \
          certonly --non-interactive --agree-tos \
          --manual --preferred-challenges dns \
          --manual-auth-hook /scripts/godaddy-dns-challenge.sh \
          --server https://acme-v02.api.letsencrypt.org/directory \
          --force-renewal \
          -d "*.${{ env.DOMAIN }}"

    - name: Restart web server
      if: success() 
      run: |
        sudo systemctl restart nginx
